/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.poc.java;

public class App {
    public String getGreeting() {
        /**
         * This is a play ground to try code and run them
         */

        return "Hello World! This is a starter App";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
